name: Build APK
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Buildozer
        uses: Luka-93/buildozer-action@v0
        with:
          command: buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Tufan-VPN-Package
          path: bin/*.apk

